name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build_linux:
    name: linux + wasm
    runs-on: ubuntu-latest
    steps:
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: mymindstorm/setup-emsdk@v14
      
      - uses: actions/checkout@v4
      
      - name: Build hot reload
        run: ./build.py -hot-reload

      - name: Build release
        run: ./build.py -release

      - name: Build debug
        run: ./build.py -debug

      - name: Build web
        run: ./build.py -web

  build_macos:
    name: macos
    strategy:
      matrix:
        os: [macos-13, macos-15]
    runs-on: ${{matrix.os}}
    steps:
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: mymindstorm/setup-emsdk@v14

      - uses: actions/checkout@v4

      - name: Build hot reload
        run: ./build.py -hot-reload

      - name: Build release
        run: ./build.py -release

      - name: Build debug
        run: ./build.py -debug

      - name: Build web
        run: ./build.py -web

  build_windows:
    name: windows
    runs-on: windows-latest
    steps:
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: mymindstorm/setup-emsdk@v14

      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build hot reload
        run: .\build.py -hot-reload

      - name: Build release
        run: .\build.py -release

      - name: Build debug
        run: .\build.py -debug

      - name: Build web
        run: .\build.py -web
